<h3>1.1 Получить информацию о наличие продукта</h3>
<?php
$id = 13;
echo "<b>ID: </b>" . $id . "<br>";
$_productStock = $block->getStockItem($id);
//print_r($_productStock->getData()); 
echo "<b>Qty: </b>" . $_productStock->getQty(); echo "<br />";
echo "<b>MinQty: </b>" . $_productStock->getMinQty(); echo "<br />";
echo "<b>MinSaleQty: </b>" . $_productStock->getMinSaleQty(); echo "<br />";
echo "<b>MaxSaleQty: </b>" . $_productStock->getMaxSaleQty(); echo "<br />";
echo "<b>IsInStock: </b>" . $_productStock->getIsInStock(); echo "<br />";
?>

<h3>1.2 Получить информацию об изображения продукта (Image)</h3>
<?php
echo "<b>ID: </b>" . $id . "<br>";
$_product = $block->getProductById($id);
echo "<b>Width: </b>" .$block->getImageOriginalWidth($_product, 'product_small_image') . '<br />'; 
echo "<b>Height: </b>" .$block->getImageOriginalHeight($_product, 'product_small_image') . '<br />';
echo "<b>Url: </b>" .$block->getImageUrl($_product, 'product_small_image') . '<br />';
?>

<h3>1.3 Получить коллекцию всех покупателей (Customers)</h3>
<?php
    $allCustomers = $this->getAllCustomers();
    foreach ($allCustomers as $customer) {
        echo "<b>ID: </b>" . $customer->getId() . "<br>";
        echo "<b>Email: </b>" . $customer->getEmail() . "<br>";
        echo "<b>Name: </b>" .$customer->getFirstname() . " " . $customer->getLastname() . "<br>";
    }
?>

<h3>1.4 Получить коллекцию заказов (Orders) по любому выбранному фильтру (status)</h3>
<?php
    
    $orderCollection = $block->getOrderCollection();
 
    if ($orderCollection && count($orderCollection)) {
        foreach ($orderCollection AS $order) {
            echo "<b>ID: </b>" . $order->getId() . "<br/>";
            echo "<b>Status: </b>" . $order->getStatus() . "<br/>";
        }
    }
?>

<h3>1.5 Получить все группы покупателей (Group Customers)</h3>
<?php
    $customerGroupCollection = $block->getCustomerGroupCollection();
    foreach($customerGroupCollection as $customerGroup) {
     echo "<b>ID: </b>" . $customerGroup->getId() . "<br/>";
     echo "<b>Group: </b> " . $customerGroup->getCode() . "<br/>";
    }
?>

<h3>1.6 Получить список методов оплаты (Payment Methods) </h3>
<?php
    $payments = $this->getPayment();
    foreach ($payments as $payment) {
      echo "<b>Payment Methods: </b>" . $payment->getTitle() . "<br/>";
    }
?>
<h3>1.7 Получить список активных методов доставки (Shipping Methods) </h3>
<?php
    $carriers = $block->getShippingMethods();
    foreach ($carriers as $carrier) {
        echo "<b>Shipping Methods: </b>" . $carrier['label'] . "<br>";
    }
?>